### ISSUE TITLE
Add support for folders and other node types

### ISSUE THREAD

**Issue by Tereza-Pytelova** [IBM/watson-assistant-workbench#100]
- [x] Add subtag `type` to `node` tag with allowed values `standard`, `event_handler`, `frame`, `slot`, `response_condition`, `folder`
- [x] Node without `type` tag will default to `standard` type in xml2json conversion
- [x] Add documentation
- [x] Add tests

**Comment by Tereza-Pytelova** [comment]
Due to vacations postponing this to the next sprint.

**Comment by Tereza-Pytelova** [comment]
within replanning this was moved to the Sprint 25

**Comment by Tereza-Pytelova** [comment]
Most of this is probably done, please revisit and finish it.

**Comment by ZoningFraction** [comment]
FYI, something about node types and their requirements can be found [here](https://cloud.ibm.com/docs/services/assistant?topic=assistant-api-dialog-modify). Should the requirements be checked in the scripts?

**Comment by Tereza-Pytelova** [comment]
Merged.
