### ISSUE TITLE
Importing nodes from another xml doesn't preseve their position

### ISSUE THREAD

**Issue by MichalPospech** [IBM/watson-assistant-workbench#130]
Importing nodes from different xml file doesnt preserve the position in the dialog (sub)tree but moves it to the end of it making the imported nodes have lowest priority. More precisely if there is a node, that has no condition or "anything_else" condition (called default node in the script), it puts the imported nodes to the end and moves the default node to the end. Otherwise it just puts the imported nodes to the end.

Demonstration:
[waw-bug.zip](https://github.com/IBM/watson-assistant-workbench/files/2282761/waw-bug.zip)

**Comment by Tereza-Pytelova** [comment]
Merged.
