### ISSUE TITLE
Update scripts to python 3

### ISSUE THREAD

**Issue by Tereza-Pytelova** [IBM/watson-assistant-workbench#146]

**Comment by cclauss** [comment]
#150 Covered a lot of the basic Python 3 issues.  It is now merged.

One of the issues that remains is Absolute Imports as discussed at:
* https://portingguide.readthedocs.io/en/latest/imports.html#absolute-imports

**Comment by Tereza-Pytelova** [comment]
@MichalPospech will not continue on this, assigning this to @AlexejPopovic instead.

**Comment by Tereza-Pytelova** [comment]
Done and merged.
