### ISSUE TITLE
Add default entity settings into config file

### ISSUE THREAD

**Issue by Tereza-Pytelova** [IBM/watson-assistant-workbench#156]
i.e. `[entities]` section.

**Comment by Tereza-Pytelova** [comment]
Due to more prioritized project moving this to the next sprint.

**Comment by Tereza-Pytelova** [comment]
Due to vacations postponing this to the next sprint.

**Comment by Tereza-Pytelova** [comment]
within replanning this was moved to the Sprint 24.

**Comment by Tereza-Pytelova** [comment]
Due to discussions postponing this to the next sprint.

**Comment by ZoningFraction** [comment]
Done, closing.
