### ISSUE TITLE
Node name generation Error when  generating from T2C

### ISSUE THREAD

**Issue by tomasmacek** [IBM/watson-assistant-workbench#161]
Currently we generate node names  in XMLHandler from intent name (we use wrong terminology here by calling it  intent rather then condition) .
However, more nodes with the same condition can exist, which is not taken care off.

We should create alternative names for subsequent nodes to make sure that node names are unique.
They should be also generated in XLSXHandler rather then XMLHandler as it is the place where labels are created and they should be assigned correct node name as well.

CC: @Tereza-Pytelova

**Comment by Tereza-Pytelova** [comment]
Postponing this to the next sprint.

**Comment by Tereza-Pytelova** [comment]
Postponing it to the Sprint 23 for review.

**Comment by tomasmacek** [comment]
This has been fixed by pull #176
