### ISSUE TITLE
Wrong terminology in T2C code

### ISSUE THREAD

**Issue by tomasmacek** [IBM/watson-assistant-workbench#162]
Currently we use wrong terminology cor referring to condition, intent and node ID in T2C part of code.
This is for historical reasons, simplifications  which are not valid any more.
This appears particularly in XML and XLS Handlers.

**Comment by Tereza-Pytelova** [comment]
Postponing this to the next sprint.

**Comment by Tereza-Pytelova** [comment]
Will be solved by #161
