### ISSUE TITLE
Convert scripts to Python 3

### ISSUE THREAD

**Issue by Tereza-Pytelova** [IBM/watson-assistant-workbench#172]
Use https://docs.python.org/2/library/2to3.html

**Comment by Tereza-Pytelova** [comment]
@MichalPospech if this is done, please close it. For now postponing this issue to the next sprint.

**Comment by cclauss** [comment]
Please do not use 2to3...  It often breaks Python 2 compatibility (#173) to get to Python 3.  I would advicate futurize (https://python-future.org) or moderize (python-modernize/python-modernize) instead.  Happy to help if that would be of interest.

**Comment by Tereza-Pytelova** [comment]
Due to nontrivial merging postponing to the next sprint.

**Comment by Tereza-Pytelova** [comment]
@MichalPospech how is it going? I'm postponing this issue to the next sprint.

**Comment by Tereza-Pytelova** [comment]
@MichalPospech will not continue on this, @AlexejPopovic please revisit what was done and complete this.

**Comment by Tereza-Pytelova** [comment]
Merged to devel, finally ;)
