### ISSUE TITLE
Preserve compatibility with Python 2.7

### ISSUE THREAD

**Issue by Tereza-Pytelova** [IBM/watson-assistant-workbench#173]
Discuss if we want scripts to be compatible with both Python 3 and 2.
-> We do if it is not huge amount of work.

**Comment by Tereza-Pytelova** [comment]
Postponing this to the next sprint.

**Comment by Tereza-Pytelova** [comment]
@MichalPospech Postponing this to the next sprint.

**Comment by Tereza-Pytelova** [comment]
@MichalPospech will not continue on this.

**Comment by cclauss** [comment]
Is this still a goal?

**Comment by Tereza-Pytelova** [comment]
No, it is not. Last WAW version which supports python 2.7 is the `1.2`.
