### ISSUE TITLE
Tests for Python3 do not pass after recent update

### ISSUE THREAD

**Issue by tomasmacek** [IBM/watson-assistant-workbench#179]
1.89s$ flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
./scripts/NodeData.py:92:98: F821 undefined name 'unicode'
        if len(rawOutputs) >= 1 and (isinstance(rawOutputs[0], str) or isinstance(rawOutputs[0], unicode)):
                                                                                                 ^
./scripts/NodeData.py:136:81: F821 undefined name 'unicode'
        if len(channel) > 0 and isinstance(channel, str) or isinstance(channel, unicode):
                                                                                ^
./scripts/NodeData.py:140:16: F821 undefined name 'unicode'
            if unicode.isdigit(channelName):
               ^
3     F821 undefined name 'unicode'

**Comment by cclauss** [comment]
Fixed in new commit to #178

**Comment by Tereza-Pytelova** [comment]
Merged, closing this.
