### ISSUE TITLE
Fix boolean conversion in json-xml-json conversion

### ISSUE THREAD

**Issue by Tereza-Pytelova** [IBM/watson-assistant-workbench#202]
When setting context variables to boolean values like true / false, they get converted to “True” and “False”, which evaluates differently in node checks.
- [x] Add `boolean` value to attribute `type`
- [x] Add documentation
- [x] Add tests

**Comment by balatjan** [comment]
XML `<variable>True<variable>` is not converted to JSON boolean `"variable": true` but to string `"variable": "True"`.

**Comment by Tereza-Pytelova** [comment]
Check if some standard attibute can be used for specification of type of tag value. If so, consider use it also for numbers (now we use custom attribute `type="number"`.

**Comment by Tereza-Pytelova** [comment]
It seems that no standard attribute can be used to parse boolean value through `lxml`. We decided to add `boolean` value to attribute `type`.

**Comment by ZoningFraction** [comment]
All done, closing.
