### ISSUE TITLE
Fix duplicated system entities when importing from multiple project folders

### ISSUE THREAD

**Issue by balatjan** [IBM/watson-assistant-workbench#209]
When having `system_entities.csv` in multiple project folders, duplicated entities (e.g., you have `sys-number` in two of you project folders) will show in resulting entities.json causing WA to reject the upload with error: 
`Unique Violation: The value "sys-number" already exists (code 400)`

**Comment by balatjan** [comment]
Also fix for other entities than system only system one.

**Comment by Tereza-Pytelova** [comment]
Done for the system ones, for regular entities it will be fixed in #300
