### ISSUE TITLE
Enable workspace creation/update/test by specifying name only

### ISSUE THREAD

**Issue by michal-mylek** [IBM/watson-assistant-workbench#211]
From our automated CI/CD process, we would need to be able to identify a particular remote workspace by its name only (~ATM "workspace_name" attribute in [conversation] section of build.cfg).  "workspace_id" will be unspecified/unused in this scenario (~depending on chosen implementation - as a switch of the script perhaps)

- [x] update script `workspace_deploy.sh`
- [x] update script `workspace_test.sh`
- [x] add documentation
- [x] add tests

**Comment by Tereza-Pytelova** [comment]
Done and merged in April.
