### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by ondrejtomas** [IBM/watson-assistant-workbench#270]
there was problem with version of pytest

**Comment by Tereza-Pytelova** [comment]
Could you be more specific in description of this issue, please? ;) (for us later and for @AlexejPopovic to investigate it from logging point of view)

**Comment by ondrejtomas** [comment]
Sure :) The problem was that the old version of pytest (that was cached in Travis CI ~3.3.0) allows check even things printed to log (using logging) by 'capture' component (that allows to read system out and err in the test), but newer versions (that we used locally and were installed by pip because we did not specify any version for pytest in requirements ~4.3.0) don't do this - there are already different 'capture' components for system out / err and log.

**Comment by Tereza-Pytelova** [comment]
Thank you ;)
