### ISSUE TITLE
Rename conversation_workspace_name_unique in scripts/workspace_deploy.py to something like 'conversation_workspace_deploy_by_name'

### ISSUE THREAD

**Issue by ondrejtomas** [IBM/watson-assistant-workbench#289]
I would just suggest to change name of this param to something like: conversation_workspace_deploy_by_name, it is the real action we tried to do and we test if the name is unique... when we change it... we just need to slightly change log output and it will make more sense:
-  'conversation_workspace_name set to unique' -> something like 'conversation_workspace_deploy_by_name is set to true -> trying deploy workspace by name'
- "'conversation_workspace_name' set to unique but not defined." -> 'conversation_workspace_deploy_by_name is set to true but no workspace name is provided (conversation_workspace_name)'

**Comment by Tereza-Pytelova** [comment]
Done in #317 
Parameter is named `conversation_workspace_match_by_name` and it is used for all uploading, deleting and testing workspaces.
