### ISSUE TITLE
Remove overwriting name and description of WA workspace by default values

### ISSUE THREAD

**Issue by ondrejtomas** [IBM/watson-assistant-workbench#29]
When I manually prepare empty workspace with filled in name and description in WA and want to just update content (I do not specify name nor description in configuration) then the name and the description is replaced by default values ('default_workspace_name' for name and empty string for description). I would suggest to remove this default values and send the workspace json without a name and description.

- [x] add tests

**Comment by Tereza-Pytelova** [comment]
Tests added, merged.
