### ISSUE TITLE
Improve functions to report JUnit XML output

### ISSUE THREAD

**Issue by ondrejtomas** [IBM/watson-assistant-workbench#294]

**Comment by ondrejtomas** [comment]
We would like to have it same for WA and CF. Here is a link for inspiration:
https://www.ibm.com/support/knowledgecenter/en/SSUFAU_1.0.0/com.ibm.rsar.analysis.codereview.cobol.doc/topics/cac_useresults_junit.html

**Comment by michal-mylek** [comment]
@ondrejtomas this just got a priority bump, because I discovered that current workaround is ignoring occasional problems / test errors altogether

**Comment by Tereza-Pytelova** [comment]
Merged.
