### ISSUE TITLE
T2C generated buttons are not interpreted properly for some versions of WA

### ISSUE THREAD

**Issue by tomasmacek** [IBM/watson-assistant-workbench#30]
Currently, the buttons added through T2C are not interpreted properly for some version of WA and number of buttons is limited to 5. 
For the time being, we need to move button representations elsewhere  (output.suggestions instead of output.generic) till the format of WA stabilize.
This involves
 - [x] updating documentation
 - [x] implementation of changes

CC: @jmacosek

**Comment by Tereza-Pytelova** [comment]
Issue for testing buttons: #32

**Comment by tomasmacek** [comment]
Fixed by pull #31 
https://github.com/IBM/watson-assistant-workbench/pull/31#pullrequestreview-122928668
