### ISSUE TITLE
Enhance testing script with (toggled) automation mode exception raising

### ISSUE THREAD

**Issue by michal-mylek** [IBM/watson-assistant-workbench#311]
Goal : Modify "evaluate_tests.py" script to optionally throw exception, when there are any failed tests detected while evaluating.
Optionality will be achieved by utilizing command line parameter

**Comment by Tereza-Pytelova** [comment]
Done in 354c63e522dcfc92e38736d8d62ae6a88ec60fdb, @ondrejtomas please do not forget to include issue number in commit messages ;)
