### ISSUE TITLE
Bez odpovědi: #CO_JE && @PREDMET:<x>

### ISSUE THREAD

**Issue by MonikaBrandejs** [IBM/watson-assistant-workbench#33]
Dotazování pomocí většího množství entit - rozpozná intent i entitu, nicméně nenabídne odpověď.

**Comment by tomasmacek** [comment]
Thanks for spotting the problem. Let us keep the issues and conversations in english. 
This is being addressed by pull request https://github.com/IBM/watson-assistant-workbench/pull/41

**Comment by Tereza-Pytelova** [comment]
@tomasmacek postponing this to the next sprint..

**Comment by Tereza-Pytelova** [comment]
@tomasmacek could you please close this?

**Comment by Tereza-Pytelova** [comment]
@tomasmacek postponing this to the next sprint..

**Comment by Tereza-Pytelova** [comment]
Postponing this to the Sprint 20.

**Comment by Tereza-Pytelova** [comment]
Postponing this to the next sprint.

**Comment by Tereza-Pytelova** [comment]
Postponing this to the next sprint.

**Comment by Tereza-Pytelova** [comment]
@tomasmacek what about closing this? :) Postponing it to the next sprint.

**Comment by tomasmacek** [comment]
This is covered by recent refactoring #176 and it is fixed, closing the issue.
