### ISSUE TITLE
Foldables

### ISSUE THREAD

**Issue by tomasmacek** [IBM/watson-assistant-workbench#34]
Clientv2 currently supports a foldable feature - a form of rendering text. Text is having its short and long form. User can select between the forms by clicking at the text.

We need to add support for this feature to T2C format

**Comment by tomasmacek** [comment]
We will support this for the time being in form of extra channel (marked as F  %%F....)
Although, this might change in the future as more appropriate form wold be some simple markup within the text.

**Comment by Tereza-Pytelova** [comment]
@tomasmacek postponing this to the next sprint..

**Comment by Tereza-Pytelova** [comment]
Isnť this done @tomasmacek ?
