### ISSUE TITLE
Add more feasible example application

### ISSUE THREAD

**Issue by Tereza-Pytelova** [IBM/watson-assistant-workbench#55]
Decide which topic is most suitable for testing.

**Comment by Tereza-Pytelova** [comment]
What about czech weather bot? @tomasmacek

**Comment by tomasmacek** [comment]
I seems that the existing apps are not suitable for the purpose. They typically depend on external services which can change or seas functioning. Output of the discussion so far is :
to use some form of ad hoc multistage chitchat. Deployment of Cloud functions should be part of the examples but can CF will be autonomous, e.g. evaluating a function or returning a string based on current time.  
CC: @Tereza-Pytelova @ondrejtomas
